from importlib import resources
from pathlib import Path


class TemplateNotFoundError(FileNotFoundError):
    pass


class ProjectExistsError(FileExistsError):
    pass


class PipelineScaffold:
    """Locates packaged templates and writes them into a project directory."""

    _TEMPLATES_PACKAGE = "haystack_cli.templates"

    def list_templates(self) -> list[str]:
        pkg = resources.files(self._TEMPLATES_PACKAGE)
        return sorted(
            item.name.removesuffix(".yaml") for item in pkg.iterdir() if item.name.endswith(".yaml")
        )

    def read_template(self, name: str) -> str:
        try:
            ref = resources.files(self._TEMPLATES_PACKAGE).joinpath(f"{name}.yaml")
            return ref.read_text(encoding="utf-8")
        except (FileNotFoundError, TypeError):
            raise TemplateNotFoundError(f"Template '{name}' not found.")

    def write_project(
        self,
        project_dir: Path,
        pipeline_template: str,
        indexing_template: str,
        context: dict[str, str],
    ) -> list[Path]:
        if project_dir.exists():
            raise ProjectExistsError(f"Directory already exists: {project_dir}")

        pipeline_yaml = self._interpolate(self.read_template(pipeline_template), context)
        indexing_yaml = self._interpolate(self.read_template(indexing_template), context)

        files: dict[Path, str] = {
            project_dir / "pipeline.yaml": pipeline_yaml,
            project_dir / "indexing.yaml": indexing_yaml,
            project_dir / ".env.example": self._build_env_example(context),
            project_dir / ".haystack" / "config.toml": self._build_project_toml(context),
            project_dir / "README.md": self._build_readme(project_dir.name),
        }

        created: list[Path] = []
        for path, content in files.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            created.append(path)

        return created

    def _interpolate(self, template: str, context: dict[str, str]) -> str:
        for key, value in context.items():
            template = template.replace(f"{{{{ {key} }}}}", value)
        return template

    def _build_env_example(self, context: dict[str, str]) -> str:
        lines: dict[str, str] = {
            "openai": "OPENAI_API_KEY=sk-...",
            "anthropic": "ANTHROPIC_API_KEY=sk-ant-...",
            "cohere": "COHERE_API_KEY=...",
            "ollama": "# No API key required for Ollama",
            "huggingface": "HUGGINGFACE_API_KEY=hf_...",
        }
        provider = context.get("llm_provider", "openai")
        return f"# Copy to .env and fill in your credentials\n{lines.get(provider, '')}\n"

    def _build_project_toml(self, context: dict[str, str]) -> str:
        return (
            "[pipeline]\n"
            'default_file = "pipeline.yaml"\n\n'
            "[document_store]\n"
            f'backend = "{context.get("document_store", "inmemory")}"\n\n'
            "[llm]\n"
            f'provider = "{context.get("llm_provider", "openai")}"\n'
        )

    def _build_readme(self, project_name: str) -> str:
        return (
            f"# {project_name}\n\n"
            "Generated by haystack-cli.\n\n"
            "## Quickstart\n\n"
            "```bash\n"
            "cp .env.example .env  # add your credentials\n"
            "haystack pipeline validate pipeline.yaml\n"
            "haystack pipeline run pipeline.yaml\n"
            "```\n"
        )
